version: '3.8'

services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: docu-mind-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: docu_mind_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - docu-mind-network

  qdrant-dev:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
    profiles:
      - local

volumes:
  postgres_data:
    driver: local
  models_cache:

networks:
  docu-mind-network:
    driver: bridge
